theme: jekyll-theme-minimal
title: Oats' Reworks
description: The utilities reworks by Oats Jenkins (https://youtube.com/c/OatsJenkins), composed in one repository
logo: https://yt3.ggpht.com/sqHtktE0q6WO4qOAw4siRM4hV6_gB9k-STIJO4ZfLSPUH_UeMm2H3mIzgmwI-VXJIrlwmRY5=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj
